// Fixed all-zero components, deliberately synthetic and never personal keys.
// Encrypted fixture uses the literal test passphrase synthetic-passphrase.
String syntheticSshKey({String? passphrase}) =>
    passphrase == null ? _plain : _encrypted;

const _plain = '''-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
QyNTUxOQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIgAAAAAAAAA
AAAAAAtzc2gtZWQyNTUxOQAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAECAwQF
-----END OPENSSH PRIVATE KEY-----
''';

const _encrypted = '''-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABAAV2KZKH
NunBjzrv+5UyLGAAAAAQAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkJBkb+NghorPKMpkc54XSR6eCLdSu6k+VUpjVO
kCyU+91/I8yd3z4EI9B02G7iT41bRtx2R4VxpYvNqkQV4qyC79s+rqS3fW8Oh6hY7s2EHo
//bqjkJvLZADvs8TTXkLFKJcgmMJfuR5HcGKNJStt0EmmEk4kvzB/IhlUkwnZem0gyOJhu
OtdyhZ2ZN7AoISqg==
-----END OPENSSH PRIVATE KEY-----
''';
